In [1]:
# Loading Dataset using Pandas
import pandas as pd

df = pd.read_csv(r"C:\Users\shubh\OneDrive\Desktop\Customer_Shopping_Behaviour\Source\customer_shopping_behavior.csv")

In [2]:
pd.set_option('display.max.rows', 4000)

In [3]:
# Top 5 rows

df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [116]:
# Summary Statistics

df.describe(include = 'all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [117]:
# Finding Null Values If Any

df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [118]:
# Inputing Missing Values in Review Ranking Column with median rating of product category

df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [119]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [120]:
# converting columns according to snake case for better readability abd documentation

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns = {'purchase_amount_(usd)' : 'purchase_amount'})

In [121]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [122]:
# create a new column age_group

labels = ['Young-Adult', 'Adult', 'Middle-Aged', 'Senior']

df['age-group'] = pd.qcut(df['age'], q=4, labels = labels)

In [123]:
df[['age','age-group']].head(10)

   age    age-group
0   55  Middle-Aged
1   19  Young-Adult
2   50  Middle-Aged
3   21  Young-Adult
4   45  Middle-Aged
5   46  Middle-Aged
6   63       Senior
7   27  Young-Adult
8   26  Young-Adult
9   57  Middle-Aged

In [124]:
# create a new column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [125]:
df[['frequency_of_purchases','purchase_frequency_days']]

     frequency_of_purchases  purchase_frequency_days
0               Fortnightly                       14
1               Fortnightly                       14
2                    Weekly                        7
3                    Weekly                        7
4                  Annually                      365
5                    Weekly                        7
6                 Quarterly                       90
7                    Weekly                        7
8                  Annually                      365
9                 Quarterly                       90
10                Bi-Weekly                       14
11              Fortnightly                       14
12              Fortnightly                       14
13                   Weekly                        7
14                   Weekly                        7
15                  Monthly                       30
16                Bi-Weekly                       14
17                Quarterly                       90
18                   Weekly                        7
19                Bi-Weekly                       14
20           Every 3 Months                       90
21                Quarterly                       90
22                 Annually                      365
23                   Weekly                        7
24                   Weekly                        7
25                 Annually                      365
26                 Annually                      365
27           Every 3 Months                       90
28           Every 3 Months                       90
29                   Weekly                        7
30                  Monthly                       30
31                  Monthly                       30
32                 Annually                      365
33                Quarterly                       90
34                Quarterly                       90
35                Bi-Weekly                       14
36              Fortnightly                       14
37                   Weekly                        7
38           Every 3 Months                       90
39                  Monthly                       30
40                Quarterly                       90
41                 Annually                      365
42                 Annually                      365
43              Fortnightly                       14
44                   Weekly                        7
45                 Annually                      365
46                Quarterly                       90
47                   Weekly                        7
48                  Monthly                       30
49                Bi-Weekly                       14
50                Bi-Weekly                       14
51                Quarterly                       90
52                   Weekly                        7
53                   Weekly                        7
54                Bi-Weekly                       14
55                 Annually                      365
56                   Weekly                        7
57              Fortnightly                       14
58                  Monthly                       30
59                   Weekly                        7
60                   Weekly                        7
61           Every 3 Months                       90
62              Fortnightly                       14
63                   Weekly                        7
64              Fortnightly                       14
65           Every 3 Months                       90
66           Every 3 Months                       90
67                  Monthly                       30
68           Every 3 Months                       90
69                   Weekly                        7
70           Every 3 Months                       90
71                 Annually                      365
72           Every 3 Months                       90
73                Bi-Weekly                       14
74                  Monthly                       30
75                 Annually                      365
76                  Monthly                       30
77              Fortnightly                       14
78              Fortnightly                       14
79           Every 3 Months                       90
80           Every 3 Months                       90
81           Every 3 Months                       90
82           Every 3 Months                       90
83                   Weekly                        7
84           Every 3 Months                       90
85                Bi-Weekly                       14
86                Bi-Weekly                       14
87              Fortnightly                       14
88                  Monthly                       30
89                Quarterly                       90
90                  Monthly                       30
91           Every 3 Months                       90
92           Every 3 Months                       90
93                   Weekly                        7
94                   Weekly                        7
95                  Monthly                       30
96           Every 3 Months                       90
97                 Annually                      365
98                 Annually                      365
99                Quarterly                       90
100             Fortnightly                       14
101               Bi-Weekly                       14
102               Quarterly                       90
103               Bi-Weekly                       14
104                 Monthly                       30
105                Annually                      365
106                 Monthly                       30
107             Fortnightly                       14
108               Bi-Weekly                       14
109             Fortnightly                       14
110             Fortnightly                       14
111                Annually                      365
112               Bi-Weekly                       14
113               Quarterly                       90
114                  Weekly                        7
115          Every 3 Months                       90
116                Annually                      365
117             Fortnightly                       14
118               Bi-Weekly                       14
119                Annually                      365
120                Annually                      365
121             Fortnightly                       14
122             Fortnightly                       14
123                  Weekly                        7
124                Annually                      365
125          Every 3 Months                       90
126          Every 3 Months                       90
127                  Weekly                        7
128             Fortnightly                       14
129               Bi-Weekly                       14
130             Fortnightly                       14
131                  Weekly                        7
132                  Weekly                        7
133                Annually                      365
134                 Monthly                       30
135               Quarterly                       90
136               Quarterly                       90
137                  Weekly                        7
138                  Weekly                        7
139                Annually                      365
140                  Weekly                        7
141                  Weekly                        7
142             Fortnightly                       14
143               Quarterly                       90
144                 Monthly                       30
145               Quarterly                       90
146             Fortnightly                       14
147             Fortnightly                       14
148                Annually                      365
149                 Monthly                       30
150          Every 3 Months                       90
151                Annually                      365
152                Annually                      365
153                Annually                      365
154               Quarterly                       90
155               Quarterly                       90
156                Annually                      365
157             Fortnightly                       14
158                 Monthly                       30
159          Every 3 Months                       90
160                 Monthly                       30
161             Fortnightly                       14
162               Bi-Weekly                       14
163                  Weekly                        7
164             Fortnightly                       14
165                 Monthly                       30
166                 Monthly                       30
167          Every 3 Months                       90
168             Fortnightly                       14
169          Every 3 Months                       90
170               Bi-Weekly                       14
171                  Weekly                        7
172               Bi-Weekly                       14
173                Annually                      365
174                Annually                      365
175                Annually                      365
176               Quarterly                       90
177                 Monthly                       30
178               Quarterly                       90
179             Fortnightly                       14
180             Fortnightly                       14
181                  Weekly                        7
182                Annually                      365
183                  Weekly                        7
184             Fortnightly                       14
185             Fortnightly                       14
186                Annually                      365
187               Bi-Weekly                       14
188               Bi-Weekly                       14
189                  Weekly                        7
190               Quarterly                       90
191          Every 3 Months                       90
192               Bi-Weekly                       14
193                Annually                      365
194               Quarterly                       90
195                 Monthly                       30
196             Fortnightly                       14
197                 Monthly                       30
198             Fortnightly                       14
199                  Weekly                        7
200                 Monthly                       30
201                Annually                      365
202                Annually                      365
203                  Weekly                        7
204               Bi-Weekly                       14
205                  Weekly                        7
206             Fortnightly                       14
207               Bi-Weekly                       14
208                 Monthly                       30
209          Every 3 Months                       90
210             Fortnightly                       14
211             Fortnightly                       14
212                Annually                      365
213          Every 3 Months                       90
214          Every 3 Months                       90
215               Bi-Weekly                       14
216                  Weekly                        7
217                Annually                      365
218               Quarterly                       90
219             Fortnightly                       14
220             Fortnightly                       14
221               Quarterly                       90
222             Fortnightly                       14
223                Annually                      365
224          Every 3 Months                       90
225                Annually                      365
226                 Monthly                       30
227             Fortnightly                       14
228                Annually                      365
229          Every 3 Months                       90
230                Annually                      365
231          Every 3 Months                       90
232               Bi-Weekly                       14
233          Every 3 Months                       90
234                  Weekly                        7
235               Quarterly                       90
236             Fortnightly                       14
237             Fortnightly                       14
238                Annually                      365
239               Bi-Weekly                       14
240             Fortnightly                       14
241               Bi-Weekly                       14
242          Every 3 Months                       90
243                 Monthly                       30
244                  Weekly                        7
245             Fortnightly                       14
246               Bi-Weekly                       14
247                  Weekly                        7
248                  Weekly                        7
249                Annually                      365
250                  Weekly                        7
251                Annually                      365
252             Fortnightly                       14
253               Bi-Weekly                       14
254               Bi-Weekly                       14
255                Annually                      365
256          Every 3 Months                       90
257               Quarterly                       90
258               Quarterly                       90
259                Annually                      365
260          Every 3 Months                       90
261                Annually                      365
262                Annually                      365
263                 Monthly                       30
264                Annually                      365
265               Bi-Weekly                       14
266                  Weekly                        7
267                Annually                      365
268                 Monthly                       30
269               Bi-Weekly                       14
270                Annually                      365
271             Fortnightly                       14
272               Bi-Weekly                       14
273               Quarterly                       90
274               Bi-Weekly                       14
275                  Weekly                        7
276             Fortnightly                       14
277               Bi-Weekly                       14
278                Annually                      365
279                 Monthly                       30
280               Bi-Weekly                       14
281               Bi-Weekly                       14
282                 Monthly                       30
283                Annually                      365
284               Quarterly                       90
285               Bi-Weekly                       14
286                Annually                      365
287             Fortnightly                       14
288               Bi-Weekly                       14
289                 Monthly                       30
290                  Weekly                        7
291                 Monthly                       30
292               Quarterly                       90
293                Annually                      365
294          Every 3 Months                       90
295               Quarterly                       90
296                  Weekly                        7
297               Bi-Weekly                       14
298          Every 3 Months                       90
299             Fortnightly                       14
300                  Weekly                        7
301          Every 3 Months                       90
302          Every 3 Months                       90
303                  Weekly                        7
304               Bi-Weekly                       14
305                Annually                      365
306                Annually                      365
307          Every 3 Months                       90
308               Bi-Weekly                       14
309             Fortnightly                       14
310             Fortnightly                       14
311                 Monthly                       30
312                Annually                      365
313          Every 3 Months                       90
314          Every 3 Months                       90
315                Annually                      365
316                 Monthly                       30
317          Every 3 Months                       90
318                Annually                      365
319          Every 3 Months                       90
320               Quarterly                       90
321               Quarterly                       90
322                 Monthly                       30
323               Bi-Weekly                       14
324               Quarterly                       90
325                Annually                      365
326                  Weekly                        7
327                  Weekly                        7
328                  Weekly                        7
329                 Monthly                       30
330               Bi-Weekly                       14
331               Quarterly                       90
332                 Monthly                       30
333               Bi-Weekly                       14
334                Annually                      365
335          Every 3 Months                       90
336                Annually                      365
337                Annually                      365
338                  Weekly                        7
339          Every 3 Months                       90
340          Every 3 Months                       90
341               Bi-Weekly                       14
342          Every 3 Months                       90
343                 Monthly                       30
344                 Monthly                       30
345                Annually                      365
346                  Weekly                        7
347             Fortnightly                       14
348             Fortnightly                       14
349               Bi-Weekly                       14
350             Fortnightly                       14
351               Bi-Weekly                       14
352          Every 3 Months                       90
353                 Monthly                       30
354                  Weekly                        7
355          Every 3 Months                       90
356                  Weekly                        7
357               Bi-Weekly                       14
358          Every 3 Months                       90
359          Every 3 Months                       90
360             Fortnightly                       14
361                Annually                      365
362             Fortnightly                       14
363             Fortnightly                       14
364          Every 3 Months                       90
365               Quarterly                       90
366             Fortnightly                       14
367                 Monthly                       30
368                 Monthly                       30
369               Quarterly                       90
370                  Weekly                        7
371                 Monthly                       30
372                  Weekly                        7
373               Bi-Weekly                       14
374                 Monthly                       30
375               Quarterly                       90

In [126]:
# top 10 rows from both columns

df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [127]:
# comparing common elements from both columns 

(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [128]:
# dropping promo_code column

df = df.drop('promo_code_used', axis = 1)

In [107]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age-group', 'purchase_frequency_days'],
      dtype='object')

## Connecting Python script to MySQL

In [131]:
!pip install pymysql sqlalchemy

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy in c:\users\shubh\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\shubh\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\shubh\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [133]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

# MySQL connection
connection_url = URL.create(
    drivername="mysql+pymysql",
    username="root",
    password="Guddu@2002",
    host="localhost",
    port=3306,
    database="customer_behavior"
)

engine = create_engine(connection_url)

# Write DataFrame to MySQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age-group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-Aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young-Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-Aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young-Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-Aged,365